# HostTools.psm1
# Wraps Windows-side .exe utilities (Claudelk, vendor CLIs, host pwsh, ...) so
# they're callable from inside the sandbox as plain Linux commands. Each
# wrapper is a 5-line bash script in /usr/local/bin/<guestCommand> that execs
# the Windows exe through WSL's binfmt_misc interop bridge.
#
# Wrappers carry the marker `# claudearium-hosttool: <name>` on line 2 so
# Get-HostToolsActualFromDistro can grep + sed them out of /usr/local/bin
# without confusing other binaries.
#
# Initialize-WslInteropService ensures the WSLInterop binfmt is registered at
# every boot — WSL2 + systemd doesn't auto-register it, see
# docs/wsl2-gotchas.md#5.
#
# Public surface:
#   Path conversion
#     ConvertTo-GuestPath   -Path  — 'C:\X\foo.exe' -> '/mnt/c/X/foo.exe'; passes /-paths
#     Resolve-DefaultGuestCommand -WindowsExe — 'C:\X\Foo.exe' -> 'sb-foo'
#   Wrapper lifecycle
#     ConvertTo-WrapperContent       — assemble the 5-line bash wrapper
#     Install-HostToolWrapper        — write /usr/local/bin/<gc> + ensure binfmt
#     Remove-HostToolWrapper         — rm /usr/local/bin/<gc>
#     Get-HostToolsActualFromDistro  — enumerate marker-bearing wrappers
#     Initialize-WslInteropService   — deploy + enable claudearium-wsl-interop.service
#   Profile mutation
#     Add-HostToolToProfile / Remove-HostToolFromProfile
#     Add-CatalogToolAsHostAttach -ProfilePath -ToolName -WindowsExe
#                                 — drop-in attach for catalog tools (gh/glab/acli/seqcli):
#                                   guestCommand = tool name, not the sb-<slug> default
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module (Join-Path $PSScriptRoot 'Wsl.psm1')
Import-Module (Join-Path $PSScriptRoot 'Profile.psm1')

$Script:WrapperMarker = '# claudearium-hosttool:'

function ConvertTo-GuestPath {
    # 'C:\Tools\Claudelk\claudelk.exe' -> '/mnt/c/Tools/Claudelk/claudelk.exe'.
    # Pass guest paths through unchanged.
    [CmdletBinding()] param([Parameter(Mandatory)][string]$Path)
    if ($Path.StartsWith('/')) { return $Path }
    if ($Path -match '^([A-Za-z]):[\\/](.*)$') {
        $drive = $Matches[1].ToLowerInvariant()
        $rest  = $Matches[2] -replace '\\', '/'
        return "/mnt/$drive/$rest"
    }
    return $Path
}

function ConvertTo-WrapperContent {
    # Build the bash wrapper text. The header carries the managed-by marker so
    # Get-HostToolsActualFromDistro can enumerate what we own without scanning
    # every binary in /usr/local/bin.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][hashtable]$ToolSpec
    )
    $name      = [string]$ToolSpec.name
    $guestExe  = ConvertTo-GuestPath -Path ([string]$ToolSpec.windowsExe)
    $winExe    = [string]$ToolSpec.windowsExe
    return @"
#!/usr/bin/env bash
$Script:WrapperMarker $name
# windowsExe: $winExe
# Auto-generated by claudearium host-tools. Do not edit by hand.
exec '$guestExe' "`$@"
"@
}

function Initialize-WslInteropService {
    # WSL2 + systemd does NOT auto-register the WSLInterop binfmt (open WSL bug);
    # without it, executing a Windows .exe from inside the distro fails with
    # 'Exec format error'. We install a tiny oneshot unit that re-registers the
    # binfmt at every boot if it isn't already there.
    [CmdletBinding()] param([Parameter(Mandatory)][string]$DistroName)
    $r = Invoke-InDistro -Name $DistroName -User 'root' -Command 'test -e /proc/sys/fs/binfmt_misc/WSLInterop' -AllowFail -CaptureOutput
    if ($r.ExitCode -eq 0) { return }

    Write-Host "  Installing WSLInterop binfmt registration (one-time)..." -ForegroundColor DarkGray
    $unit = @'
[Unit]
Description=Register WSL Windows Interop binfmt
DefaultDependencies=no
After=systemd-binfmt.service
ConditionPathExists=/proc/sys/fs/binfmt_misc/register

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'test -e /proc/sys/fs/binfmt_misc/WSLInterop || echo ":WSLInterop:M::MZ::/init:PF" > /proc/sys/fs/binfmt_misc/register'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
'@
    $normalized = ($unit -replace "`r`n", "`n")
    $b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($normalized))
    # 'systemctl --now' has been observed to hang in WSL2 + systemd; split into
    # daemon-reload + enable + an immediate manual register so the running session
    # picks up the binfmt without waiting for the unit's ExecStart.
    $cmd = "set -e; " +
           "printf '%s' '$b64' | base64 -d > /etc/systemd/system/claudearium-wsl-interop.service; " +
           "systemctl daemon-reload; " +
           "systemctl enable claudearium-wsl-interop.service >/dev/null 2>&1; " +
           "test -e /proc/sys/fs/binfmt_misc/WSLInterop || " +
           "echo ':WSLInterop:M::MZ::/init:PF' > /proc/sys/fs/binfmt_misc/register"
    Invoke-InDistro -Name $DistroName -User 'root' -Command $cmd
}

function Install-HostToolWrapper {
    # Install /usr/local/bin/<guestCommand> as root, 0755. Also makes sure
    # WSL's .exe binfmt is registered (one-time).
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$DistroName,
        [Parameter(Mandatory)][hashtable]$ToolSpec
    )
    Initialize-WslInteropService -DistroName $DistroName

    $guestCmd = [string]$ToolSpec.guestCommand
    $content  = ConvertTo-WrapperContent -ToolSpec $ToolSpec
    # Parens around the -replace: without them, pwsh parses GetBytes(x -replace a, b)
    # as GetBytes(x-replace-a, b) and complains about two args.
    $normalized = ($content -replace "`r`n", "`n")
    $b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($normalized))
    $dest = "/usr/local/bin/$guestCmd"
    $cmd = "set -e; printf '%s' '$b64' | base64 -d > '$dest'; chmod 0755 '$dest'"
    Invoke-InDistro -Name $DistroName -User 'root' -Command $cmd
}

function Remove-HostToolWrapper {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$DistroName,
        [Parameter(Mandatory)][string]$GuestCommand
    )
    $dest = "/usr/local/bin/$GuestCommand"
    Invoke-InDistro -Name $DistroName -User 'root' -Command "rm -f '$dest'" -AllowFail | Out-Null
}

function Get-HostToolsActualFromDistro {
    # Enumerate wrappers carrying our marker. Returns @( @{ name; guestCommand;
    # windowsExe } ).
    [CmdletBinding()] param([Parameter(Mandatory)][string]$DistroName)
    # grep -l + awk to extract the name + windowsExe header lines. List files
    # that have our marker on line 2 specifically (it always lives there).
    $cmd = "grep -l '^# claudearium-hosttool:' /usr/local/bin/* 2>/dev/null || true"
    $r = Invoke-InDistro -Name $DistroName -User 'claude' -Command $cmd -AllowFail -CaptureOutput
    if ($r.ExitCode -ne 0) { return @() }
    $files = @($r.Output | Where-Object { $_ -is [string] -and $_.Trim() -match '^/usr/local/bin/' } | ForEach-Object { $_.Trim() })
    if ($files.Count -eq 0) { return @() }

    $result = @()
    foreach ($f in $files) {
        # Read lines 2-3 verbatim — parsing prefixes in PowerShell is much
        # simpler than getting awk's quoting through pwsh -> wsl argv intact.
        $rr = Invoke-InDistro -Name $DistroName -User 'claude' -Command "sed -n '2,3p' '$f'" -AllowFail -CaptureOutput
        if ($rr.ExitCode -ne 0) { continue }
        $lines = @($rr.Output | Where-Object { $_ -is [string] -and $_.Trim().StartsWith('#') } | ForEach-Object { $_.ToString().Trim() })
        $name = ''
        $win  = ''
        foreach ($l in $lines) {
            if ($l -match '^# claudearium-hosttool:\s*(.+)$') { $name = $Matches[1].Trim() }
            if ($l -match '^# windowsExe:\s*(.+)$')              { $win  = $Matches[1].Trim() }
        }
        if (-not $name) { continue }
        $result += @{
            name         = $name
            guestCommand = (Split-Path -Leaf $f)
            windowsExe   = $win
        }
    }
    return ,$result
}

function Add-HostToolToProfile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ProfilePath,
        [Parameter(Mandatory)][hashtable]$ToolSpec
    )
    $spec = if (Test-Path $ProfilePath) { Read-Profile -Path $ProfilePath -Raw } else {
        @{
            schemaVersion = 1
            distro        = @{ name = 'claudearium'; base = 'debian-12'; installPath = '%LOCALAPPDATA%\WSL\claudearium' }
        }
    }
    if (-not $spec.ContainsKey('hostTools') -or -not $spec.hostTools) { $spec['hostTools'] = @() }
    $existing = @($spec.hostTools)
    $gc = [string]$ToolSpec.guestCommand
    $kept = @($existing | Where-Object { [string]$_.guestCommand -ne $gc })
    $spec.hostTools = @($kept) + @($ToolSpec)
    Write-Profile -Path $ProfilePath -Spec $spec
}

function Remove-HostToolFromProfile {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ProfilePath,
        [Parameter(Mandatory)][string]$GuestCommand
    )
    if (-not (Test-Path $ProfilePath)) { return $false }
    $spec = Read-Profile -Path $ProfilePath -Raw
    if (-not $spec.ContainsKey('hostTools') -or -not $spec.hostTools) { return $false }
    $existing = @($spec.hostTools)
    $before = $existing.Count
    $spec.hostTools = @($existing | Where-Object { [string]$_.guestCommand -ne $GuestCommand })
    if (@($spec.hostTools).Count -eq $before) { return $false }
    Write-Profile -Path $ProfilePath -Spec $spec
    return $true
}

function Add-CatalogToolAsHostAttach {
    # Attach a catalog tool (gh/glab/acli/seqcli) from the Windows host using
    # the bare tool name as the guestCommand — so users get drop-in `gh`
    # instead of `sb-gh`. Test-Profile refuses the resulting profile if the
    # same name is also enabled in tools.<name>, which would collide on PATH.
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ProfilePath,
        [Parameter(Mandatory)][string]$ToolName,
        [Parameter(Mandatory)][string]$WindowsExe
    )
    $spec = @{
        name         = $ToolName
        windowsExe   = $WindowsExe
        guestCommand = $ToolName
    }
    Add-HostToolToProfile -ProfilePath $ProfilePath -ToolSpec $spec
}

function Resolve-DefaultGuestCommand {
    # 'C:\Tools\Claudelk\claudelk.exe' -> 'sb-claudelk'.
    [CmdletBinding()] param([Parameter(Mandatory)][string]$WindowsExe)
    $leaf = [IO.Path]::GetFileNameWithoutExtension($WindowsExe)
    if (-not $leaf) { return 'sb-tool' }
    $slug = ($leaf -replace '[^A-Za-z0-9-]', '').ToLowerInvariant()
    if (-not $slug) { $slug = 'tool' }
    return "sb-$slug"
}

Export-ModuleMember -Function `
    ConvertTo-GuestPath, `
    ConvertTo-WrapperContent, `
    Initialize-WslInteropService, `
    Install-HostToolWrapper, `
    Remove-HostToolWrapper, `
    Get-HostToolsActualFromDistro, `
    Add-HostToolToProfile, `
    Remove-HostToolFromProfile, `
    Add-CatalogToolAsHostAttach, `
    Resolve-DefaultGuestCommand
